[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "master"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "master"
[[override]]
  name = "k8s.io/api"
  branch = "master"
[[override]]
  name = "k8s.io/apiserver"
  branch = "master"
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "master"
[[override]]
  name = "k8s.io/cli-runtime"
  branch = "master"
[[override]]
  name = "k8s.io/client-go"
  branch = "master"
[[override]]
  name = "k8s.io/cloud-provider"
  branch = "master"
[[override]]
  name = "k8s.io/cluster-bootstrap"
  branch = "master"
[[override]]
  name = "k8s.io/csi-api"
  branch = "master"
[[override]]
  name = "k8s.io/kube-aggregator"
  branch = "master"

# Doesn't do proper releases.
[[override]]
  name = "k8s.io/kube-openapi"
  branch = "master"

# Also no proper releases.
[[override]]
  name = "k8s.io/utils"
  branch = "master"

[[override]]
  # kubernetes/pkg/util/parsers/parsers.go needs the new reference.ParseNormalizedNamed
  # API call, which isn't yet in any stable release.
  name = "github.com/docker/distribution"
  branch = "master"
